### ISSUE TITLE
Display only upcoming events on bottom of the homepage

### ISSUE THREAD

**Issue by kirsten** [luncheonette/the-sunview#10]
From Dylan:

>  the events list at the bottom should just be for upcoming events and nothing when there are none, add date info.

**Comment by dgoats** [comment]
The only thing I guess here is what happens when there are no upcoming events?  Does it then display past events?

**Comment by kirsten** [comment]
Good question! I think the easiest options are probably:

1. Just hide the entire section (including the "What's Happening" header) if there is nothing upcoming
2. Display a message underneath the header/rsvp info saying that there is nothing upcoming (perhaps with a link to the page that shows all events)
3. Always display the "newest" 5 or 10 events, which would include past and upcoming (we can add dates and/or styles to distinguish - could be the same as the event page styles)

I'd maybe vote for 2 or 3, since those seem like they'd be the most consistent to people visiting the site to see if there are any upcoming events.

Displaying past events if there are no upcoming ones is totally doable too, it's just a little more dev work (since it's a static site I'd have to write some javascript to grab past events from another page, parse them, and render them to the homepage).

**Comment by dgoats** [comment]
I like #1 or #2, esp since we often have member events coming up that aren't public, but if there's nothing public coming up on the site, better that people just see nothing coming up. I like better #2, giving them notice rather than just having it blank...

Dylan

_Sent from my Samsung SM-G930T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kirsten** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Only display upcoming events on homepage](https://trello.com/c/DGFKw5nK/5-only-display-upcoming-events-on-homepage)

**Comment by kirsten** [comment]
This is done! Since it's kind of hard to see what it looks like when there are no upcoming events, here's a screenshot:

![screen shot 2017-08-25 at 2 01 20 pm](https://user-images.githubusercontent.com/775748/29726846-696ebbdc-899f-11e7-8469-16f461bbe499.png)

Happy to change the wording to anything - just let me know!

**Comment by dgoats** [comment]
Oh that's awesome.  Maybe the text on that could be:

"Nothing coming up right now.  <link>Things that have happened recently.</link>"

**Comment by kirsten** [comment]
Sounds good. Done!
