### ISSUE TITLE
Add link for image on home page to content?

### ISSUE THREAD

**Issue by dgoats** [luncheonette/the-sunview#13]
Hi K!
Can we add a link so people don't have to click "keep reading" but can just click the whole thing (image + text) for the main splash items on the homepage?
Thanks!
![screen shot 2017-08-16 at 12 48 40 pm](https://user-images.githubusercontent.com/7450909/29374983-62feaef8-8281-11e7-9d22-cee3ef5584fc.png)

**Comment by kirsten** [comment]
Oh yes! Good idea. I keep thinking we should do that and then forgetting :)

**Comment by kirsten** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make entire post preview clickable target on homepage](https://trello.com/c/IleP0Gi4/3-make-entire-post-preview-clickable-target-on-homepage)
