### ISSUE TITLE
Add "about" to S.L.S.C. link

### ISSUE THREAD

**Issue by dgoats** [luncheonette/the-sunview#21]
Can we add this page?

http://thesunview.org/about/

This isn't really an "issue" but I am not sure how to add so a page so it also ends up in menu?
THX
D

**Comment by kirsten** [comment]
Added! https://the-sunview.netlify.com/about/

There isn't currently a way to edit what appears in the menu in the Netlify CMS. For the time being, it's probably easiest if I just manually edit the menu as needed (it's super fast to do so). I can also create a way for to make that editable in the CMS, just might not happen right away this week.

**Comment by dgoats** [comment]
ok!  I think it's OK so long as it's easily editable in github...

!
-D
​
