### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by dgoats** [luncheonette/the-sunview#22]
Quick q - should I play with the menu/titles?  I wasn't sure if I should update anything at the moment since you're working, or even exactly where to update - but if it's not trouble, would love to 

1. change "gatherings" to "**what's here**" and 
2. move "rentals" into the s.l.s.c.r. menu (at the bottom) 
3. add welcometothesunview.tumblr.com in the S.L.S.C. menu above social club research (can call the link Tumblr)

if it's not hard to do so?  We'd rather have rentals not be the first thing people see, but it's useful to have the page come up in search results, etc...

Thanks again for all Kirsten!

-D

**Comment by kirsten** [comment]
Hey, I made these changes too! Let me know if it all looks right? For now it's fast and easy for me to make these changes, but I'll look into adding that functionality to the CMS as well.
