### ISSUE TITLE
Caption on images?

### ISSUE THREAD

**Issue by dgoats** [luncheonette/the-sunview#25]
hi Kirsten - sorry to keep adding issues! Do you think we can add a "caption field" on posts so we can add captions to whatever the main image on a post is?  It could appear in small text beneath the image?

No hurry on this - future if it's tough.

Thanks!
D

**Comment by kirsten** [comment]
Totally, that’s easy to do! I’ll add it this weekend 🙂

**Comment by kirsten** [comment]
Image captions have been added! You can see one in action here: https://the-sunview.netlify.com/5pairings/

**Comment by dgoats** [comment]
radness !
