### ISSUE TITLE
Language for homepage

### ISSUE THREAD

**Issue by dgoats** [luncheonette/the-sunview#3]
Here is our current mission statement.  Because it's long, I broke into two sections:

1. (for top of page)
The Sunview Luncheonette is a storefront on pause, a member-based social club, a microvenue for art, poetics, regionalism, mutual aid, and commoning. It is resistant to traditional forms of commerce, commodification, and gentrification. It is above all, an “approach,” and least of all, an “outcome.” It is unknown. It is hopeful. It saves you a seat at the counter.

2. (for above event listings)
The Luncheonette performs semi-public dinners, talks, work-shops, lectures, plays, reading groups, and musical interludes in a semi-private setting. All members are invited to attend. Non-members, please RSVP at hello@thesunview.org.

**Comment by kirsten** [comment]
I updated these on the homepage: https://luncheonette.github.io/the-sunview/ Does that look right to you?

I think we can eventually make all this content CMS-editable. Though...I'm guessing it doesn't change all that often, so maybe that's lower priority.
