### ISSUE TITLE
Netlify CMS - delete an event?

### ISSUE THREAD

**Issue by dgoats** [luncheonette/the-sunview#37]
Is it possible? :) Or do we just delete from github?
No hurry, just posting here.
Want to zap this one:
Secrets of the Intoxicated Life Divulged in Greenpoint
D

**Comment by kirsten** [comment]
Hey! I just updated to the newest version of Netlify so you should be able to delete thru the CMS now.

**Comment by dgoats** [comment]
Awesome!!

On Jan 2, 2018 11:14 PM, "Kirsten Nordine" <notifications@github.com> wrote:

Closed #37 <https://github.com/luncheonette/the-sunview/issues/37>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/luncheonette/the-sunview/issues/37#event-1407260942>,
or mute the thread
