### ISSUE TITLE
Netlify doesn't format dates in the way Jekyll expects

### ISSUE THREAD

**Issue by kirsten** [luncheonette/the-sunview#51]
Jekyll depends on a certain date format to sort the event posts, but the `event_date` field in Netlify's CMS returns a date in a different format. This causes lots of build failures right now.

**Comment by dgoats** [comment]
Ah! I was wondering why... ok good to know!

**Comment by kirsten** [comment]
Okay, this should be fixed now. I'll keep an eye out just in case, though!
